// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRFFdqPUhDY_3MDn2AJ8zxYfkrZv-ML9w',
    appId: '1:187122410721:web:1a12492abff387db27c3a0',
    messagingSenderId: '187122410721',
    projectId: 'challengebot-b9411',
    authDomain: 'challengebot-b9411.firebaseapp.com',
    storageBucket: 'challengebot-b9411.firebasestorage.app',
    measurementId: 'G-TMCQSXN9P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB6Z0pzJTgZwyyBRwUcdLJfVNId5M_alY',
    appId: '1:187122410721:android:bf832b0d6c61880127c3a0',
    messagingSenderId: '187122410721',
    projectId: 'challengebot-b9411',
    storageBucket: 'challengebot-b9411.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3LWB61H0d9ecfBiARe3TV6iYYT6Q3wMg',
    appId: '1:187122410721:ios:08e8f4aaa72a2d7027c3a0',
    messagingSenderId: '187122410721',
    projectId: 'challengebot-b9411',
    storageBucket: 'challengebot-b9411.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3LWB61H0d9ecfBiARe3TV6iYYT6Q3wMg',
    appId: '1:187122410721:ios:08e8f4aaa72a2d7027c3a0',
    messagingSenderId: '187122410721',
    projectId: 'challengebot-b9411',
    storageBucket: 'challengebot-b9411.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRFFdqPUhDY_3MDn2AJ8zxYfkrZv-ML9w',
    appId: '1:187122410721:web:29ebc3665740370927c3a0',
    messagingSenderId: '187122410721',
    projectId: 'challengebot-b9411',
    authDomain: 'challengebot-b9411.firebaseapp.com',
    storageBucket: 'challengebot-b9411.firebasestorage.app',
    measurementId: 'G-3Z7FVH97BY',
  );
}